trigger:
  branches:
    include:
      -main

pool: 
  vmImage: "ubuntu-latest"

variables:

steps:
-task: TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: "1.5.0"
  
-script: |
    terraform init
    display: "Terraform Init"

-script: |
    terraform plan -out=tfplan
    display: "Terraform Plan"

-script: |
    terraform apply tfplan
    display: "Terraform Apply"