trigger:
  branches:
    include:
      - main

pool: 
  vmImage: 'ubuntu-latest'

steps:
  
- script: |
    terraform init
    display: 'Terraform Init'

- script: |
    terraform plan -out=tfplan
    display: 'Terraform Plan'

- script: |
    terraform apply tfplan
    display: 'Terraform Apply'